config/routes.rb
Rails.application.routes.draw do
  resources :games do
    collection do
      get 'update_game_grid'
    end
  end
  #get "/games/update_game_grid", :as => 'update_game_grid'

  devise_for :players

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :player do
    # root to: "devise/sessions#new"
    unauthenticated do
      root to: "devise/sessions#new"
    end
    authenticated do
      root to: "home#index" , as: :authenticated_root
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'home#index'

  get 'system/unsubscribe', as: 'unsubscribe'
  get 'system/about_us', as: 'about_us'
  get 'system/privacy_policy', as: 'privacy_policy'
  get 'system/terms_of_use', as: 'terms_of_use'
  get 'system/contact_us', as: 'contact_us'
  get 'system/faq', as: 'faq'


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params[:game_over]
      game = Game.find(params[:game_over])
      flash.now[:notice] = "You Won ... congrats!" if game.game_status != "lost"
      flash.now[:notice] = "You Lost ... sorry :(" if game.game_status == "lost"
    end
    @games = current_player.games
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Play Online</h1>
<p>
  <a class="btn btn-primary btn-lg" href="<%= new_game_path()%>" role="button" data-ng-if="isAuthenticated">New Game</a>
</p>


<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th class="header" data-href="" rel="tooltip" title="">Game status</th>
      <th class="header" data-href="" rel="tooltip" title="">Player Name</th>
      <th class="header" data-href="" rel="tooltip" title="">Player Email</th>
      <th class="header" data-href="" rel="tooltip" title="">Action</th>
    </tr>
  </thead>
  <tbody>
    <%@games.each do |game|%>
      <tr >
        <td ><%= link_to game.game_status || "Playing", game_path(:id => game) ,title: "Show"%></td>
        <td ><%= game.player%></td>
        <td ><%= game.player.try(:email)%></td>
        <td>
          <%= link_to raw("<i class='fa fa-info-circle' aria-hidden='true'></i>"), game_path(:id => game) ,title: "Show"%>
          <%= link_to raw("<i class='fa fa-trash' aria-hidden='true'></i>"), game_path(:id => game ),method: :delete, data: { confirm: 'Are you sure?' }  ,title: "Delete"%>
        </td>
      </tr>
    <%end%>
  </tbody>
</table>