config/routes.rb
Rails.application.routes.draw do
  resources :games do
    collection do
      get 'update_game_grid'
    end
  end
  #get "/games/update_game_grid", :as => 'update_game_grid'

  devise_for :players

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :player do
    # root to: "devise/sessions#new"
    unauthenticated do
      root to: "devise/sessions#new"
    end
    authenticated do
      root to: "home#index" , as: :authenticated_root
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'home#index'

  get 'system/unsubscribe', as: 'unsubscribe'
  get 'system/about_us', as: 'about_us'
  get 'system/privacy_policy', as: 'privacy_policy'
  get 'system/terms_of_use', as: 'terms_of_use'
  get 'system/contact_us', as: 'contact_us'
  get 'system/faq', as: 'faq'


end

app/models/game.rb
class Game < ApplicationRecord

  belongs_to :player,
  class_name: "Player",
  foreign_key: :player_id
  validates :p45_game_id,:player_id ,presence: true

  has_many :salvos, class_name: "Salvo",foreign_key: :platform45_game_id, dependent: :destroy
  has_many :ships, class_name: "Ship",foreign_key: :platform45_game_id, dependent: :destroy

  after_create :create_ships

  def ship_name_sink(name)
    ship_to_sink = ships.alive.where(:name => name).first
    ship_to_sink.sink! if ship_to_sink
  end

  def move_game(coords={})
    unless game_status
      if x = coords[:x] and y = coords[:y]
        nuke(x,y)
      else
        nuke(*salvos.next_shot)
      end
    end
  end

  def nuke(x,y)
    params = {:id => p45_game_id, :x => x.to_i, :y => y.to_i}
    resp = CreateGameService.new.nuke(params, Rails.logger)
    if resp.code.to_i == 200
      data = JSON.parse(resp.body)
      salvos.fires_status(x,y,data["status"],data["sunk"]) if data["status"]
      salvos.received_enemy_fire(data["x"], data["y"]) if data["x"] and data["y"]
      # update game status when needed
      update_attribute(:game_status, data["game_status"]) if data["game_status"]
      update_attribute(:game_status, data["prize"]) if data["prize"]
    else
      raise "Error nuking: #{resp.body}"
    end
  end

  def game_over?
    !game_status.blank?
  end

  def create_ships
    [{"Carrier"     => 5}, {"Battleship" => 4}, {"Destroyer"   => 3},
     {"Submarine"   => 2}, {"Submarine"  => 2}, {"Patrol Boat" => 1},
     {"Patrol Boat" => 1}].each do |ship_info|
      ships.create!(:name => ship_info.keys.first, :length => ship_info.values.first)
    end
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  respond_to :html, :js

  def index
    if params[:game_over]
      game = Game.find(params[:game_over])
      flash.now[:notice] = "You Won ... congrats!" if game.game_status != "lost"
      flash.now[:notice] = "You Lost ... sorry :(" if game.game_status == "lost"
    end
    @games = current_player.games
  end

  def new
    @game = CreateGameService.new.process(current_player, Rails.logger)
    if @game.errors.any?
      flash[:error] = @game.errors.first
      redirect_to new_game_url
    else
      redirect_to game_url(@game)
    end
  end

  def show
    @game = Game.find(params[:id])
    # default to manually
    @manually_play = params[:manually] == "false" ? false : true
    @game.move_game unless @manually_play
  end

  def update_game_grid
    @game = Game.find(params[:id])
    @game.move_game(:x => params[:x], :y => params[:y])
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    respond_to do |format|
      flash.now[:notice] = "Game is successfully deleted"
      format.html { redirect_to games_url }
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_player_grid.html.erb
<h4><strong><%= heading%></strong></h4>
<table>
  <%10.times do |y|%>
    <tr>
      <%10.times do |x|%>
        <%if shots.map(&:coordinates).include? [x,y]%>
          <%shot = shots.find{|s| s.coordinates == [x,y]}%>
          <td title="shot" class="miss"></td>
        <%else%>
           <td title="<%= [x,y].join(" , ")%>" align="center"><%=link_to "x", update_game_grid_games_path(:id => @game.id, :x => x, :y => y), :title => "Play x:#{x}, y:#{y}", :remote => true ,class: "click_play"%></td>
        <%end%>
      <%end%>
    </tr>
  <%end%>
</table>

app/views/games/new.html.erb
<h1>Games#new</h1>
<p>Find me in app/views/games/new.html.erb</p>

app/views/games/show.html.erb
<h1>Playing Game</h1>
<div class="row" id="playing_game">
  <div class="col-md-6 grid" id="enemy_grid">
    <%=render "player_grid", :heading => "Their Board:", :shots => @game.salvos.ours%>
  </div>
  <div class="col-md-6 grid" id="friendly_grid">
    <%=render "player_grid", :heading => "My Board:", :shots => @game.salvos.enemy%>
  </div>
</div>


<div id="legend">
  <h3>Legend Grid</h3>
  <%unless @game.game_over?%>
    <% if @manually_play%>
      <%= link_to "Auto Play", game_path(:id => @game, :manually => false),class: "ng-pristine btn btn-primary ng-scope",id: "auto_play"%>
    <%else%>
      <%= link_to "Manual Play", game_path(:id => @game, :manually => true),class: "ng-pristine btn btn-primary ng-scope",id: "manual_play"%>
    <%end%>
    <input id="game_id" name "game_id" value="<%= @game.id%>" type="hidden" />
  <%end%>
  <%= link_to "List My Games", games_path(),class: "ng-pristine btn btn-primary ng-scope",id: "auto_play"%>
</div>
<%= content_for :head do%>
  <%= stylesheet_link_tag "play"%>
  <%unless @game.game_over? or @manually_play%>
     <div id="manually_play"></div>
     <%= javascript_include_tag 'jquery.periodicalupdater','play'%>
     <script>
       $(document).ready(function() {
         $.PeriodicalUpdater("#{update_grid_path}", {
           method: 'get',
           data: {id: "#{@game.id}"},
           minTimeout: 1500,
           maxTimeout: 4000
         });
       });
     </script>
  <%end%>
<%end%>

app/views/games/update_game_grid.js.erb
<%if @game.game_over?%>
  window.location.href = "/games?game_over=<%=@game.id%>"
<%else%>
  $("#friendly_grid").html("<%= escape_javascript render(:partial => 'games/player_grid', :locals => { :shots => @game.salvos.enemy ,:heading => 'My Board:'}) %>");
  $("#enemy_grid").html("<%= escape_javascript render(:partial => 'games/player_grid', :locals => { :shots => @game.salvos.ours ,:heading => 'Their Board:'}) %>");
<%end%>